name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # يشغل الـ pipeline عند أي push على فرع main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sallyjaber2/simple-fastapi:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 54.166.204.162
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd /home/ubuntu/simple-fastapi
            docker pull sallyjaber2/simple-fastapi:latest
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d -p 8000:8000 --name fastapi-app sallyjaber2/simple-fastapi:latest

